In [ ]:
start_year=2022
print(start_year)
type(start_year)

In [ ]:
goodbye_message='Hasta pronto'
print(goodbye_message)
type(goodbye_message)

In [80]:
abs(-1)



1

In [ ]:
round(5.6398)

In [ ]:
round(5.8974596, 2)

In [ ]:
round(5.8974596, 5)

In [ ]:
total_items=100
sold_items=25
total_items=total_items-sold_items
print(total_items)

In [ ]:
total_items=100
sold_items=25
total_items-=sold_items
print(total_items)

In [ ]:
#Salto de línea
msg = ' Primera línea \n Segunda línea \n Tercera línea'
print(msg)


In [ ]:
#Tabulador
msg = 'Valor = \t40'
print(msg)


In [ ]:
#Comilla simple
msg = 'Necesitamos \'escapar\' la comilla simple'
print(msg)

In [ ]:
#Barra invertida
msg = 'Capítulo \\ Sección \\ Encabezado'
print(msg)

In [ ]:
msg1 = '¿Sabes por qué estoy acá?'
msg2 = 'Porque me apasiona'
print(msg1, msg2)
print(msg1, msg2, sep='|')
print(msg2, end='!!')


In [ ]:
name = input('Introduzca su nombre: ')


In [ ]:
name

In [ ]:
type(name)

In [ ]:
age = input('Introduzca su edad: ')

In [ ]:
age

In [ ]:
type(age)

In [58]:
proverb1 = 'Cuando el río suena'
proverb2 = 'agua lleva'
proverb1 + proverb2

'Cuando el río suenaagua lleva'

In [59]:
proverb1 + ', ' + proverb2

'Cuando el río suena, agua lleva'

In [63]:
reaction = 'Wow '
reaction*4

'Wow Wow Wow Wow '

In [64]:
#Indexación en los strings
sentence = 'Hola, mundo'
sentence[0]

'H'

In [65]:
sentence[-1]

'o'

In [66]:
sentence[4]

','

In [67]:
sentence[-5]

'm'

In [68]:
sentence[5]

' '

In [69]:
sentence[:]

'Hola, mundo'

In [72]:
sentence[2:]

'la, mundo'

In [76]:
sentence[:4]

'Hola'

In [77]:
sentence[2:5]

'la,'

In [79]:
sentence[2:7:2]

'l,m'

In [ ]:
proverb = 'Lo cortés no quita lo valiente'
len(proverb)

In [ ]:
empty = ''
len(empty)

In [ ]:
proverb = 'Más vale malo conocido que bueno por conocer'

In [ ]:
'malo' in proverb

In [ ]:
'bueno' in proverb

In [ ]:
'regular' in proverb

In [ ]:
dna_sequence = 'ATGAAATTGAAATGGGA'

In [ ]:
not('C' in dna_sequence) #Primera aproximación

In [ ]:
'C' not in dna_sequence #Forma  pitónica

In [ ]:
#Dividir una cadena 
proverb = 'No hay mal que por bien no venga'
proverb.split()

In [ ]:
tools = 'Martillo,Sierra,Destornillador'
tools.split(',')

In [ ]:
#Limpiar cadenas
serial_number = '\n\t   \n 48374983274832   \n\n\t  \t   \n'

In [ ]:
serial_number.strip()

In [ ]:
serial_number.lstrip()

In [ ]:
serial_number.rstrip()

In [ ]:
#Búsquedas 

#lyrics.startswith('Quizás')
#lyrics.endswith('Final')

#lyrics.find('amor')
#lyrics.index('amor')

#lyrics.count('mi')

In [ ]:
proverb = 'Quien mal anda mal acaba'
proverb.replace('mal', 'bien')

In [ ]:
proverb.replace('mal', 'bien', 1)

In [ ]:
proverb.replace('mal', 'bien', 2)

In [ ]:
#Mayúsculas y minúsculas

proverb = 'Quien a buen árbol se arrima Buena Sombra le cobija'
proverb

In [ ]:
proverb.capitalize()

In [ ]:
proverb.title()

In [ ]:
proverb.upper()

In [ ]:
proverb.lower()

In [ ]:
proverb.swapcase()

In [ ]:
#Detectar si todos los caracteres son letras
'abc'.isalpha()

In [ ]:
'a-b-c'.isalpha()

In [ ]:
#Detectar si todos los caracteres son números
'314'.isnumeric() 

In [ ]:
'3.14'.isnumeric()

In [ ]:
#Detectar si todos los caracteres son letras o números
'R2D2'.isalnum()

In [ ]:
'C3-P0'.isalnum()

In [ ]:
#Detectar mayúsculas y minúsculas
'BIG'.isupper()

In [ ]:
'Big'.isupper()

In [ ]:
'small'.islower()

In [ ]:
'First Heading'.istitle()

In [ ]:
#Condicional 'if y else'
temperature = 20
if temperature > 35:
    print('Aviso por alta temperatura')
else:
    print('Parámetros normales')

In [ ]:
#Cuando queremos condiciones dentro de condiciones
temperature = 28
if temperature < 20:
    if temperature < 10:
        print('Nivel azul')
    else:
        print('Nivel verde')
else:
    if temperature < 30:
        print('Nivel naranja')
    else:
        print('Nivel rojo')

In [ ]:
#Sustituyendo con elif
temperature = 48
if temperature < 20:
    if temperature < 10:
        print('Nivel azul')
    else:
        print('Nivel verde')
elif temperature < 30:
        print('Nivel naranja')
else:
    print('Nivel rojo')

In [ ]:
#Operadores de comparación
value = 8
value == 8

In [ ]:
value != 8

In [ ]:
value < 12

In [ ]:
value <= 7

In [ ]:
value > 4

In [ ]:
value >= 9

In [ ]:
#Entre otras condiciones
x = 8
x > 4 or x > 12

In [ ]:
x > 4 and x > 12

In [ ]:
not(x != 8)

In [ ]:
4 <= value <= 12

In [ ]:
#Booleanos en condiciones
is_cold = True
if is_cold == True:
    print('Coge chaqueta')
else:
    print('Usa camiseta')

In [ ]:
is_cold = True
if is_cold:
    print('Coge chaqueta')
else:
    print('Usa camiseta')

In [ ]:
is_cold = False
if not is_cold:  #Equivalente a is_cold == False
    print('Coge chaqueta')
else:
    print('Usa camiseta')

In [ ]:
#Bucle While 
value = 1
while value <= 4:
    print(value)
    value += 1

In [ ]:
#Romper ciclo while con break
num = 20
while num >= 1:
    if num % 3 == 0:
        print(num)
        break
    num -= 1

In [ ]:
#Comprobar la rotura del ciclo
num = 8
while num >= 1:
    if num % 9 == 0:
        print(f'{num} is a multiple of 9!')
        break
    num -=1 
else:
    print('No multiples of 9 found!')
        

In [ ]:
#Continuar un bucle
num = 21
while num >= 1:
    num -= 1
    if num % 3 == 0:
        continue
    print(num, end=', ') #Evitar salto de línea

In [ ]:
#Ciclo for
word = 'Python'
for letter in word:
    print(letter, end = ' ')

In [ ]:
#Romper un bucle for
word = 'Python'
for letter in word:
    if letter == 't':
        break
    print(letter)

In [50]:
#Iterar un rango de números
for i in range(3):
    print(i)

0
1
2


In [49]:
for i in range(1, 6, 2):
    print(i)

1
3
5


In [51]:
for _ in range(10):
    print('Repeat me 10 times!')

Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!
Repeat me 10 times!


In [57]:
#Bucles anidados
for i in range(1, 10):
    for j in range(1, 10):
        result = i * j
    print(result)    

9
18
27
36
45
54
63
72
81


# Ejercicios de condicionales

## Ejercicio 1

Escribir un programa que almacene la cadena de caracteres contraseña en una variable, pregunte al usuario por la contraseña e imprima por pantalla si la contraseña introducida por el usuario coincide con la guardada en la variable sin tener en cuenta mayúsculas y minúsculas.

In [9]:
key = 'hola'
password = input('Introduce la contraseña \n')
if key == password:
    print('Contraseña correcta')
else:
    print('Contraseña incorrecta, intente de nuevo')

Introduce la contraseña 
hola
Contraseña correcta


## Ejercicio 2

Escribir un programa que pida al usuario dos números y muestre por pantalla su división. Si el divisor es cero el programa debe mostrar un error.

In [15]:
num1 = float(input('Escriba el dividendo: \n'))
num2 = float(input('Escriba el divisor: \n'))
if num2 == 0:
    print('¡Ha ocurrido un error!')
else:
    print(num1/num2)


Escriba el dividendo: 
10
Escriba el divisor: 
5
2.0


## Ejercicio 3

Escribir un programa que pida al usuario un número entero y muestre por pantalla si es par o impar.

In [20]:
num = int(input('Escribe un número: \n'))
if num % 2 == 0:
    print(f'El número {num} es par')
else:
    print(f'El número {num} es impar')

Escribe un número: 
96
El número 96 es par


## Ejercicio 4

Para tributar un determinado impuesto se debe ser mayor de 16 años y tener unos ingresos iguales o superiores a 1000 € mensuales. Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que tributar o no.

In [23]:
age = int(input('Enter your age: \n'))
income = int(input('Enter your monthly incomes: \n€'))

if age > 16 and income >= 1000:
    print('Es necesario tributar')
else:
    print('No debes tributar')


Enter your age: 
56
Enter your monthly incomes: 
€5000
Es necesario tributar


## Ejercicio 5

Los alumnos de un curso se han dividido en dos grupos A y B de acuerdo al sexo y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su nombre y sexo, y muestre por pantalla el grupo que le corresponde.

In [48]:
name = input('Enter your name\n')
gender = input('Enter your gender (M or F)\n')

if gender == 'F':
    if name.lower() < 'n':
        print('Grupo A')
    else:
        print('Grupo B')
elif gender == 'M':
    if name.lower() > 'm':
        print('Grupo A')
    else:
        print('Grupo B')
    

             

Enter your name
marta
Enter your gender (M or F)
F
Grupo A


## Ejercicio 6

Los tramos impositivos para la declaración de la renta en un determinado país son los siguientes:

    Renta	              Tipo impositivo
Menos de 10000€	                5%
Entre 10000€ y 20000€	       15%
Entre 20000€ y 35000€	       20%
Entre 35000€ y 60000€	       30%
Más de 60000€	               45%

Escribir un programa que pregunte al usuario su renta anual y muestre por pantalla el tipo impositivo que le corresponde.

In [8]:
revenue = int(input('Write your annual income \n€'))
if revenue < 10000:
    print('Tax bracket of 5%')
    tax=5
elif revenue >= 10000 and revenue < 20000:
    print('Tax bracket of 15%')
    tax=15
elif revenue >= 20000 and revenue < 35000:
    print('Tax bracket of 20%')
    tax=20
elif revenue >= 35000 and revenue < 60000:
    print('Tax bracket of 30%')
    tax=30
elif revenue >= 60000:
    print('Tax bracket of 45%')
    tax=45

print('The tax to pay is', (tax*revenue/100), '€')

Write your annual income 
€50000
Tax bracket of 30%
The tax to pay is 15000.0 €


## Ejercicio 7

En una determinada empresa, sus empleados son evaluados al final de cada año. Los puntos que pueden obtener en la evaluación comienzan en 0.0 y pueden ir aumentando, traduciéndose en mejores beneficios. Los puntos que pueden conseguir los empleados pueden ser 0.0, 0.4, 0.6 o más, pero no valores intermedios entre las cifras mencionadas. A continuación se muestra una tabla con los niveles correspondientes a cada puntuación. La cantidad de dinero conseguida en cada nivel es de 2.400€ multiplicada por la puntuación del nivel.

  Nivel	           Puntuación
Inaceptable	          0.0
Aceptable	          0.4
Meritorio	       0.6 o más

Escribir un programa que lea la puntuación del usuario e indique su nivel de rendimiento, así como la cantidad de dinero que recibirá el usuario.

In [16]:
name = input('Enter username: \n')
score = float(input("Enter the user's score: \n"))

if score >= 0.0 and score < 0.4:
    performance = 'unacceptable'
elif score >= 0.4 and score < 0.6:
    performance = 'acceptable'
elif score >= 0.6:
    performance = 'meritorious'

print(name, 'your performance is', performance, 'and your payment will be of %.2f' % (score*2400))

Enter username: 
Fernando
Enter the user's score: 
0.986524
Fernando your performance is meritorious and your payment will be of 2367.66


# Ejercicios de bucles

## Ejercicio 1

Escribir un programa que pida al usuario una palabra y la muestre por pantalla 10 veces.

In [28]:
word = input('Escribe una palabra \n')
for i in range(1, 10):
    print(word)

Escribe una palabra 
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola


## Ejercicio 2 

Escribir un programa que pregunte al usuario su edad y muestre por pantalla todos los años que ha cumplido (desde 1 hasta su edad).

In [33]:
age = int(input('Enter your age: \n'))

for i in range(age+1):
    print(f'You have turned {i} years old')

Enter your age: 
5
You have turned 0 years old
You have turned 1 years old
You have turned 2 years old
You have turned 3 years old
You have turned 4 years old
You have turned 5 years old


## Ejercicio 3

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla todos los números impares desde 1 hasta ese número separados por comas.

In [43]:
num = int(input('Enter a positive integer: \n'))

for i in range(num+1):
    if i % 2 == 0:
        continue
    else:
        print(i, end =', ')

Enter a positive integer: 
9
1, 3, 5, 7, 9, 

In [44]:
num = int(input('Enter a positive integer: \n'))

for i in range(1, num+1, 2):
    print(i, end =', ')

Enter a positive integer: 
7
1, 3, 5, 7, 

## Ejercicio 4 

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla la cuenta atrás desde ese número hasta cero separados por comas.

In [60]:
num = int(input('Enter a positive integer: \n'))

for i in range(num, -1, -1):
    print(i, end =', ')

Enter a positive integer: 
5
5, 4, 3, 2, 1, 0, 

## Ejercicio 5 

Escribir un programa que pregunte al usuario una cantidad a invertir, el interés anual y el número de años, y muestre por pantalla el capital obtenido en la inversión cada año que dura la inversión.

In [73]:
investment = float(input('Enter the amount to invest: \n$'))
percentage = float(input('Enter the annual percentage interest: \n'))
years = int(input("Enter the number of years that you're going to invest: \n"))

for i in range(years):
    investment *= percentage/100
    print(i+1, '%.2f' % investment)
    

Enter the amount to invest: 
$1000
Enter the annual percentage interest: 
10
Enter the number of years that you're going to invest: 
5
1 100.00
2 10.00
3 1.00
4 0.10
5 0.01


In [7]:
x = 5
y = 3
z = 2
for i in range(x+1):
    z *= y
    print(i+1, z)

1 6
2 18
3 54
4 162
5 486
6 1458


## Ejercicio 6

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo, de altura el número introducido.

In [2]:
triangle_size = int(input('Enter the size of the triangle: \n'))

for i in range(triangle_size):
    for j in range(i+1):
        print('*', end = "")
    print("")

Enter the size of the triangle: 
6
*
**
***
****
*****
******


## Ejercicio 7

Escribir un programa que muestre por pantalla la tabla de multiplicar del 1 al 10.

In [5]:
for i in range(1,11):
    for j in range(1,11):
        print(i, '*', j, '=', i*j)
    print('')

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90

10 * 1 = 10
10 

## Ejercicio 8

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo.

1
3 1
5 3 1
7 5 3 1
9 7 5 3 1

In [32]:
size_triangle = int(input('Enter the size of the triangle: '))

for i in range(1, size_triangle+1, 2):
    for j in range(i, 0, -2): 
        print(j, end = ' ')
    print('')

Enter the size of the triangle: 9
1 
3 1 
5 3 1 
7 5 3 1 
9 7 5 3 1 


## Ejercicio (Series Fibonacci)

In [1]:
num = int(input('Escribe el número: '))


    

    

Escribe el número: 5


# Ejercicios ciclo while

## Ejercicio 1

Escriba un programa que pregunte una y otra vez si desea continuar con el programa, siempre que se conteste exactamente sí (en minúsculas y con tilde).

In [7]:
confirm = input('Diga sí para continuar \n')

while(confirm == 'sí'):
    print('¿Desea continuar el programa?')

print('Hasta luego')
    

Diga sí para continuar 
sí
Hasta luego


# Udemy course (Python master programming and development)

Arithmetic operators
()
**
* / 
+ - 

### Casting

In [1]:
x = 5
type(x)

int

In [2]:
x = float(x)
print(x)

5.0


In [3]:
type(x)

float

### Methods

In [4]:
x = 'water'
x.upper()

'WATER'

In [5]:
dir('string')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [6]:
x.title()

'Water'

In [7]:
x = 'WATER'
x.lower()

'water'

### Indexing and slicing

In [8]:
x = 'water'
x[1]

'a'

In [9]:
x[-1]

'r'

In [12]:
x = 'Hola como estas'
x.replace('o', 'i')

'Hila cimi estas'

In [13]:
x = 'Hola como estas'
x[1:5]

'ola '

In [14]:
x[6:8]

'om'

In [15]:
x[-8:-2]

'mo est'

In [16]:
x[-8:-1]

'mo esta'

In [17]:
x[-8:0]

''

In [18]:
x[-1]

's'

In [19]:
x[-8:]

'mo estas'

### String

In [3]:
x = ["dev", "sports", 33]
z = f"My name is {x[0]} and my hobbie is playing {x[1]} and my age is {x[2]}"
print(z)

My name is dev and my hobbie is playing sports and my age is 33


### List

In [4]:
x = ['dev', 'blue', 'green', 'yellow', 'black', 3, 4.3]
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [5]:
x[2]

'green'

In [6]:
len(x)

7

In [7]:
x.pop()

4.3

In [8]:
x

['dev', 'blue', 'green', 'yellow', 'black', 3]

In [9]:
x.append(9)

In [10]:
x

['dev', 'blue', 'green', 'yellow', 'black', 3, 9]

In [11]:
x.remove('yellow')

In [12]:
x

['dev', 'blue', 'green', 'black', 3, 9]

In [13]:
del x #Delete list

### Tuples

In [15]:
x = ('red', 'blue', 'green', 'yellow', 'black', 12, 4.3)
x[2]
#Tuples cannot be modified x.append(2) is not possible

'green'

In [16]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [17]:
len(x)

7

### Methos and functions

In [1]:
x='water'
x.upper()

'WATER'

In [2]:
dir('string')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [4]:
x.title()

'Water'

### List

In [6]:
x = ['red', 'blue', 'green', 'yellow', 'black', 3, 4.3]
dir(list)


['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [7]:
x[2]

'green'

In [8]:
x[-1]

4.3

In [9]:
len(x)

7

# Numpy


In [10]:
import numpy as np

#### 2D array

In [12]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
y = np.array(x)

In [15]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 3D array

In [16]:
x=[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [17]:
x

[[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]

In [18]:
y = np.array(x)

In [19]:
y

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

### Methods for numpy

In [20]:
import numpy as np

In [21]:
x = [1,2,3,4,5]

In [22]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
np.array(x)

array([1, 2, 3, 4, 5])

In [24]:
x

[1, 2, 3, 4, 5]

In [25]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

i for colums 
j for rows
i = j -> square matrix

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.zeros((3,5)) + 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [32]:
np.zeros((3,5)) - 5

array([[-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.]])

In [35]:
np.zeros(((4,5,2))) + 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Identity matrix

In [38]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])