In [2]:
start_year=2022
print(start_year)
type(start_year)

2022


int

In [3]:
goodbye_message='Hasta pronto'
print(goodbye_message)
type(goodbye_message)

Hasta pronto


str

In [4]:
abs(-1)



1

In [5]:
round(5.6398)

6

In [6]:
round(5.8974596, 2)

5.9

In [7]:
round(5.8974596, 5)

5.89746

In [8]:
total_items=100
sold_items=25
total_items=total_items-sold_items
print(total_items)

75


In [9]:
total_items=100
sold_items=25
total_items-=sold_items
print(total_items)

75


In [10]:
#Salto de línea
msg = ' Primera línea \n Segunda línea \n Tercera línea'
print(msg)


 Primera línea 
 Segunda línea 
 Tercera línea


In [11]:
#Tabulador
msg = 'Valor = \t40'
print(msg)


Valor = 	40


In [12]:
#Comilla simple
msg = 'Necesitamos \'escapar\' la comilla simple'
print(msg)

Necesitamos 'escapar' la comilla simple


In [13]:
#Barra invertida
msg = 'Capítulo \\ Sección \\ Encabezado'
print(msg)

Capítulo \ Sección \ Encabezado


In [14]:
msg1 = '¿Sabes por qué estoy acá?'
msg2 = 'Porque me apasiona'
print(msg1, msg2)
print(msg1, msg2, sep='|')
print(msg2, end='!!')


¿Sabes por qué estoy acá? Porque me apasiona
¿Sabes por qué estoy acá?|Porque me apasiona
Porque me apasiona!!

In [15]:
name = input('Introduzca su nombre: ')


Introduzca su nombre: Fer


In [16]:
name

'Fer'

In [17]:
type(name)

str

In [19]:
age = input('Introduzca su edad: ')

Introduzca su edad: 5


In [ ]:
age

In [ ]:
type(age)

In [ ]:
proverb1 = 'Cuando el río suena'
proverb2 = 'agua lleva'
proverb1 + proverb2

In [ ]:
proverb1 + ', ' + proverb2

In [ ]:
reaction = 'Wow '
reaction*4

In [ ]:
#Indexación en los strings
sentence = 'Hola, mundo'
sentence[0]

In [ ]:
sentence[-1]

In [ ]:
sentence[4]

In [ ]:
sentence[-5]

In [ ]:
sentence[5]

In [ ]:
sentence[:]

In [ ]:
sentence[2:]

In [ ]:
sentence[:4]

In [ ]:
sentence[2:5]

In [ ]:
sentence[2:7:2]

In [ ]:
proverb = 'Lo cortés no quita lo valiente'
len(proverb)

In [ ]:
empty = ''
len(empty)

In [ ]:
proverb = 'Más vale malo conocido que bueno por conocer'

In [ ]:
'malo' in proverb

In [ ]:
'bueno' in proverb

In [ ]:
'regular' in proverb

In [ ]:
dna_sequence = 'ATGAAATTGAAATGGGA'

In [ ]:
not('C' in dna_sequence) #Primera aproximación

In [ ]:
'C' not in dna_sequence #Forma  pitónica

In [ ]:
#Dividir una cadena 
proverb = 'No hay mal que por bien no venga'
proverb.split()

In [ ]:
tools = 'Martillo,Sierra,Destornillador'
tools.split(',')

In [ ]:
#Limpiar cadenas
serial_number = '\n\t   \n 48374983274832   \n\n\t  \t   \n'

In [ ]:
serial_number.strip()

In [ ]:
serial_number.lstrip()

In [ ]:
serial_number.rstrip()

In [ ]:
#Búsquedas 

#lyrics.startswith('Quizás')
#lyrics.endswith('Final')

#lyrics.find('amor')
#lyrics.index('amor')

#lyrics.count('mi')

In [ ]:
proverb = 'Quien mal anda mal acaba'
proverb.replace('mal', 'bien')

In [ ]:
proverb.replace('mal', 'bien', 1)

In [ ]:
proverb.replace('mal', 'bien', 2)

In [ ]:
#Mayúsculas y minúsculas

proverb = 'Quien a buen árbol se arrima Buena Sombra le cobija'
proverb

In [ ]:
proverb.capitalize()

In [ ]:
proverb.title()

In [ ]:
proverb.upper()

In [ ]:
proverb.lower()

In [ ]:
proverb.swapcase()

In [ ]:
#Detectar si todos los caracteres son letras
'abc'.isalpha()

In [ ]:
'a-b-c'.isalpha()

In [ ]:
#Detectar si todos los caracteres son números
'314'.isnumeric() 

In [ ]:
'3.14'.isnumeric()

In [ ]:
#Detectar si todos los caracteres son letras o números
'R2D2'.isalnum()

In [ ]:
'C3-P0'.isalnum()

In [ ]:
#Detectar mayúsculas y minúsculas
'BIG'.isupper()

In [ ]:
'Big'.isupper()

In [ ]:
'small'.islower()

In [ ]:
'First Heading'.istitle()

In [ ]:
#Condicional 'if y else'
temperature = 20
if temperature > 35:
    print('Aviso por alta temperatura')
else:
    print('Parámetros normales')

In [ ]:
#Cuando queremos condiciones dentro de condiciones
temperature = 28
if temperature < 20:
    if temperature < 10:
        print('Nivel azul')
    else:
        print('Nivel verde')
else:
    if temperature < 30:
        print('Nivel naranja')
    else:
        print('Nivel rojo')

In [ ]:
#Sustituyendo con elif
temperature = 48
if temperature < 20:
    if temperature < 10:
        print('Nivel azul')
    else:
        print('Nivel verde')
elif temperature < 30:
        print('Nivel naranja')
else:
    print('Nivel rojo')

In [ ]:
#Operadores de comparación
value = 8
value == 8

In [ ]:
value != 8

In [ ]:
value < 12

In [ ]:
value <= 7

In [ ]:
value > 4

In [ ]:
value >= 9

In [ ]:
#Entre otras condiciones
x = 8
x > 4 or x > 12

In [ ]:
x > 4 and x > 12

In [ ]:
not(x != 8)

In [ ]:
4 <= value <= 12

In [ ]:
#Booleanos en condiciones
is_cold = True
if is_cold == True:
    print('Coge chaqueta')
else:
    print('Usa camiseta')

In [ ]:
is_cold = True
if is_cold:
    print('Coge chaqueta')
else:
    print('Usa camiseta')

In [ ]:
is_cold = False
if not is_cold:  #Equivalente a is_cold == False
    print('Coge chaqueta')
else:
    print('Usa camiseta')

In [ ]:
#Bucle While 
value = 1
while value <= 4:
    print(value)
    value += 1

In [ ]:
#Romper ciclo while con break
num = 20
while num >= 1:
    if num % 3 == 0:
        print(num)
        break
    num -= 1

In [ ]:
#Comprobar la rotura del ciclo
num = 8
while num >= 1:
    if num % 9 == 0:
        print(f'{num} is a multiple of 9!')
        break
    num -=1 
else:
    print('No multiples of 9 found!')
        

In [ ]:
#Continuar un bucle
num = 21
while num >= 1:
    num -= 1
    if num % 3 == 0:
        continue
    print(num, end=', ') #Evitar salto de línea

In [ ]:
#Ciclo for
word = 'Python'
for letter in word:
    print(letter, end = ' ')

In [ ]:
#Romper un bucle for
word = 'Python'
for letter in word:
    if letter == 't':
        break
    print(letter)

In [ ]:
#Iterar un rango de números
for i in range(3):
    print(i)

In [ ]:
for i in range(1, 6, 2):
    print(i)

In [ ]:
for _ in range(10):
    print('Repeat me 10 times!')

In [ ]:
#Bucles anidados
for i in range(1, 10):
    for j in range(1, 10):
        result = i * j
    print(result)    

# Ejercicios de condicionales

## Ejercicio 1

Escribir un programa que almacene la cadena de caracteres contraseña en una variable, pregunte al usuario por la contraseña e imprima por pantalla si la contraseña introducida por el usuario coincide con la guardada en la variable sin tener en cuenta mayúsculas y minúsculas.

In [ ]:
key = 'hola'
password = input('Introduce la contraseña \n')
if key == password:
    print('Contraseña correcta')
else:
    print('Contraseña incorrecta, intente de nuevo')

## Ejercicio 2

Escribir un programa que pida al usuario dos números y muestre por pantalla su división. Si el divisor es cero el programa debe mostrar un error.

In [ ]:
num1 = float(input('Escriba el dividendo: \n'))
num2 = float(input('Escriba el divisor: \n'))
if num2 == 0:
    print('¡Ha ocurrido un error!')
else:
    print(num1/num2)


## Ejercicio 3

Escribir un programa que pida al usuario un número entero y muestre por pantalla si es par o impar.

In [ ]:
num = int(input('Escribe un número: \n'))
if num % 2 == 0:
    print(f'El número {num} es par')
else:
    print(f'El número {num} es impar')

## Ejercicio 4

Para tributar un determinado impuesto se debe ser mayor de 16 años y tener unos ingresos iguales o superiores a 1000 € mensuales. Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que tributar o no.

In [ ]:
age = int(input('Enter your age: \n'))
income = int(input('Enter your monthly incomes: \n€'))

if age > 16 and income >= 1000:
    print('Es necesario tributar')
else:
    print('No debes tributar')


## Ejercicio 5

Los alumnos de un curso se han dividido en dos grupos A y B de acuerdo al sexo y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su nombre y sexo, y muestre por pantalla el grupo que le corresponde.

In [ ]:
name = input('Enter your name\n')
gender = input('Enter your gender (M or F)\n')

if gender == 'F':
    if name.lower() < 'n':
        print('Grupo A')
    else:
        print('Grupo B')
elif gender == 'M':
    if name.lower() > 'm':
        print('Grupo A')
    else:
        print('Grupo B')
    

             

## Ejercicio 6

Los tramos impositivos para la declaración de la renta en un determinado país son los siguientes:

    Renta	              Tipo impositivo
Menos de 10000€	                5%
Entre 10000€ y 20000€	       15%
Entre 20000€ y 35000€	       20%
Entre 35000€ y 60000€	       30%
Más de 60000€	               45%

Escribir un programa que pregunte al usuario su renta anual y muestre por pantalla el tipo impositivo que le corresponde.

In [ ]:
revenue = int(input('Write your annual income \n€'))
if revenue < 10000:
    print('Tax bracket of 5%')
    tax=5
elif revenue >= 10000 and revenue < 20000:
    print('Tax bracket of 15%')
    tax=15
elif revenue >= 20000 and revenue < 35000:
    print('Tax bracket of 20%')
    tax=20
elif revenue >= 35000 and revenue < 60000:
    print('Tax bracket of 30%')
    tax=30
elif revenue >= 60000:
    print('Tax bracket of 45%')
    tax=45

print('The tax to pay is', (tax*revenue/100), '€')

## Ejercicio 7

En una determinada empresa, sus empleados son evaluados al final de cada año. Los puntos que pueden obtener en la evaluación comienzan en 0.0 y pueden ir aumentando, traduciéndose en mejores beneficios. Los puntos que pueden conseguir los empleados pueden ser 0.0, 0.4, 0.6 o más, pero no valores intermedios entre las cifras mencionadas. A continuación se muestra una tabla con los niveles correspondientes a cada puntuación. La cantidad de dinero conseguida en cada nivel es de 2.400€ multiplicada por la puntuación del nivel.

  Nivel	           Puntuación
Inaceptable	          0.0
Aceptable	          0.4
Meritorio	       0.6 o más

Escribir un programa que lea la puntuación del usuario e indique su nivel de rendimiento, así como la cantidad de dinero que recibirá el usuario.

In [ ]:
name = input('Enter username: \n')
score = float(input("Enter the user's score: \n"))

if score >= 0.0 and score < 0.4:
    performance = 'unacceptable'
elif score >= 0.4 and score < 0.6:
    performance = 'acceptable'
elif score >= 0.6:
    performance = 'meritorious'

print(name, 'your performance is', performance, 'and your payment will be of %.2f' % (score*2400))

# Ejercicios de bucles

## Ejercicio 1

Escribir un programa que pida al usuario una palabra y la muestre por pantalla 10 veces.

In [ ]:
word = input('Escribe una palabra \n')
for i in range(1, 10):
    print(word)

## Ejercicio 2 

Escribir un programa que pregunte al usuario su edad y muestre por pantalla todos los años que ha cumplido (desde 1 hasta su edad).

In [ ]:
age = int(input('Enter your age: \n'))

for i in range(age+1):
    print(f'You have turned {i} years old')

## Ejercicio 3

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla todos los números impares desde 1 hasta ese número separados por comas.

In [ ]:
num = int(input('Enter a positive integer: \n'))

for i in range(num+1):
    if i % 2 == 0:
        continue
    else:
        print(i, end =', ')

In [ ]:
num = int(input('Enter a positive integer: \n'))

for i in range(1, num+1, 2):
    print(i, end =', ')

## Ejercicio 4 

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla la cuenta atrás desde ese número hasta cero separados por comas.

In [ ]:
num = int(input('Enter a positive integer: \n'))

for i in range(num, -1, -1):
    print(i, end =', ')

## Ejercicio 5 

Escribir un programa que pregunte al usuario una cantidad a invertir, el interés anual y el número de años, y muestre por pantalla el capital obtenido en la inversión cada año que dura la inversión.

In [ ]:
investment = float(input('Enter the amount to invest: \n$'))
percentage = float(input('Enter the annual percentage interest: \n'))
years = int(input("Enter the number of years that you're going to invest: \n"))

for i in range(years):
    investment *= percentage/100
    print(i+1, '%.2f' % investment)
    

In [ ]:
x = 5
y = 3
z = 2
for i in range(x+1):
    z *= y
    print(i+1, z)

## Ejercicio 6

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo, de altura el número introducido.

In [ ]:
triangle_size = int(input('Enter the size of the triangle: \n'))

for i in range(triangle_size):
    for j in range(i+1):
        print('*', end = "")
    print("")

## Ejercicio 7

Escribir un programa que muestre por pantalla la tabla de multiplicar del 1 al 10.

In [ ]:
for i in range(1,11):
    for j in range(1,11):
        print(i, '*', j, '=', i*j)
    print('')

## Ejercicio 8

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo.

1
3 1
5 3 1
7 5 3 1
9 7 5 3 1

In [ ]:
size_triangle = int(input('Enter the size of the triangle: '))

for i in range(1, size_triangle+1, 2):
    for j in range(i, 0, -2): 
        print(j, end = ' ')
    print('')

# Ejercicios ciclo while

## Ejercicio 1

Escriba un programa que pregunte una y otra vez si desea continuar con el programa, siempre que se conteste exactamente sí (en minúsculas y con tilde).

In [ ]:
confirm = input('Diga sí para continuar \n')

while(confirm == 'sí'):
    print('¿Desea continuar el programa?')

print('Hasta luego')
    

# Udemy course (Python master programming and development)

Arithmetic operators
()
**
* / 
+ - 

### Casting

In [ ]:
x = 5
type(x)

In [ ]:
x = float(x)
print(x)

In [ ]:
type(x)

### Methods

In [ ]:
x = 'water'
x.upper()

In [ ]:
dir('string')

In [ ]:
x.title()

In [ ]:
x = 'WATER'
x.lower()

### Indexing and slicing

In [ ]:
x = 'water'
x[1]

In [ ]:
x[-1]

In [ ]:
x = 'Hola como estas'
x.replace('o', 'i')

In [ ]:
x = 'Hola como estas'
x[1:5]

In [ ]:
x[6:8]

In [ ]:
x[-8:-2]

In [ ]:
x[-8:-1]

In [ ]:
x[-8:0]

In [ ]:
x[-1]

In [ ]:
x[-8:]

### String

In [ ]:
x = ["dev", "sports", 33]
z = f"My name is {x[0]} and my hobbie is playing {x[1]} and my age is {x[2]}"
print(z)

### List

In [ ]:
x = ['dev', 'blue', 'green', 'yellow', 'black', 3, 4.3]
dir(list)

In [ ]:
x[2]

In [ ]:
len(x)

In [ ]:
x.pop()

In [ ]:
x

In [ ]:
x.append(9)

In [ ]:
x

In [ ]:
x.remove('yellow')

In [ ]:
x

In [ ]:
del x #Delete list

### Tuples

In [ ]:
x = ('red', 'blue', 'green', 'yellow', 'black', 12, 4.3)
x[2]
#Tuples cannot be modified x.append(2) is not possible

In [ ]:
dir(tuple)

In [ ]:
len(x)

### Methos and functions

In [ ]:
x='water'
x.upper()

In [ ]:
dir('string')

In [ ]:
x.title()

### List

In [ ]:
x = ['red', 'blue', 'green', 'yellow', 'black', 3, 4.3]
dir(list)


In [ ]:
x[2]

In [ ]:
x[-1]

In [ ]:
len(x)

# Numpy


In [ ]:
import numpy as np

#### 2D array

In [ ]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
x

In [ ]:
y = np.array(x)

In [ ]:
y

#### 3D array

In [ ]:
x=[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [ ]:
x

In [ ]:
y = np.array(x)

In [ ]:
y

### Methods for numpy

In [46]:
import numpy as np

In [47]:
x = [1,2,3,4,5]

In [48]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [49]:
np.array(x)

array([1, 2, 3, 4, 5])

In [50]:
x

[1, 2, 3, 4, 5]

In [51]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

i for colums 
j for rows
i = j -> square matrix

In [52]:
np.zeros(3)

array([0., 0., 0.])

In [53]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.zeros((3,5)) + 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [55]:
np.zeros((3,5)) - 5

array([[-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5.]])

In [56]:
np.zeros(((4,5,2))) + 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [57]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Identity matrix

In [58]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(50).reshape(5, 10)
#5 rows, 10 columns
#2D matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

-----------------------

In [ ]:
import numpy as np

In [ ]:
x = [1,2,3,4,5]

In [64]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [65]:
x = np.array(x)

In [67]:
x.max()

5

In [68]:
x.min()

1

In [70]:
np.random.rand(5)
#Random values between zero and one

array([0.33901895, 0.45457069, 0.52785402, 0.27333509, 0.15608976])

In [71]:
np.random.randn(5)
#Randn from negative values

array([-0.46296385,  1.63167902,  0.34818359, -0.24474531, -0.43963706])